ignore:
  - "*/python?.?/*"
  - "*/migrations/*"
  - "*tests*"
  - "*manage*"
  - "*manage.py"
  - "*apps.py*"
  - "*/apps.py*"
  - "*production.py*"
  - "*staging.py*"
  - "*admin*"
  - "*__init__*"
  - "*migrations*"
  - "*/settings/.*"
  - "*settings*"
  - "*urls.py*"
  - "*Procfile*"
  - "*db.sqlite*"
  - "*wsgi.py"
  - "*/wsgi.py"